### ISSUE TITLE
If session is over user might want to get noticed about it instead of seeing a blank screen

### ISSUE THREAD

**Issue by PerfectPixel** [d-i-p/customer-portal-ui#25]

**Comment by ulich** [comment]
Did you forget to register the 
```
import {authService} from "element-customer-portal-sdk";

authService.registerLoginRequiredHandler(() => {
    window.location.href = '/'
})
```
inside your app?

This one is responsible for handling this case. See https://github.com/d-i-p/customer-portal-ui/blob/master/README.md#using-it

**Comment by tarcon** [comment]
I wrote this issue, thats something i observed while testing. 
I think fixing this is part of a error-handling sdk story that i added to jira. So we can remove this here.

**Comment by tarcon** [comment]
I see you fixed that already. Even better. Disregard.

**Comment by PerfectPixel** [comment]
I'll close this then.
